In [40]:
import numpy as np

## Exercise 1

In [41]:
# random numpy array of shape (100,100)
my_array = np.random.rand(100, 100)  
print("Array: ", my_array)

Array:  [[0.83958654 0.51579904 0.39917999 ... 0.84109413 0.38222452 0.35794622]
 [0.19188387 0.06102919 0.11512997 ... 0.23162006 0.54549656 0.52421428]
 [0.33109747 0.53640828 0.9035169  ... 0.5262293  0.36070726 0.87128106]
 ...
 [0.49340771 0.1616652  0.50647441 ... 0.06628213 0.79786768 0.68080584]
 [0.51531933 0.59397001 0.0036463  ... 0.78820506 0.55408016 0.49082053]
 [0.01002502 0.83634883 0.72966436 ... 0.73194894 0.1494904  0.97570184]]


In [42]:
# get the square root of each element
sqrt_array = np.sqrt(my_array)  
print("Square Root Array:", sqrt_array)

Square Root Array: [[0.91628955 0.71819151 0.63180692 ... 0.91711184 0.61824309 0.59828607]
 [0.43804551 0.24704087 0.33930808 ... 0.48126922 0.73857739 0.72402644]
 [0.5754107  0.73239899 0.95053506 ... 0.72541664 0.6005891  0.93342437]
 ...
 [0.70242986 0.40207611 0.71167016 ... 0.25745316 0.89323439 0.8251096 ]
 [0.71785746 0.7706945  0.06038459 ... 0.88780914 0.74436561 0.70058584]
 [0.10012503 0.91452109 0.85420394 ... 0.85554015 0.38663988 0.98777621]]


In [43]:
# get the sum of all the square roots
sum_sqrt = np.sum(sqrt_array)  
print("Sum of all square roots", sum_sqrt)

Sum of all square roots 6697.017675269051


## Exercise 2

In [44]:
from numpy import genfromtxt
my_data = genfromtxt('RandomeValues.csv', delimiter=',')
print(my_data)

[[ 68.  54.  95.  65.  68.   6.  50.  63.  99.  81.  14.]
 [  5.  85.  83.  22.  39.  26.  73.  77.  97.  75.  33.]
 [  1.  46.  39.  53.  67.  19.  87.   3.  84.  58.  26.]
 [ 83.  81.  31.  96.  13.   3.  58.  32. 100. 100.  96.]
 [ 71.   2.  63.  84.  85.   5.  67.  35.  76.  77.  76.]
 [ 79.  67.  44. 100.  89.  71.  27.  46.  45.  13.  32.]
 [100.  27.  23.  76.  53.  86.   2.  59.  30.  52.   2.]
 [ 37.  43.  10.  16.  77.  40.  62.   4.  22.  64.  15.]
 [ 97.  61.   8.  99.  67.  42.  59.   7.  86.  42.  21.]
 [ 80.  93.  76.  46.  46.  35.  57.  70.  93.  36.  86.]
 [ 25.  23.  89.  58.  89.  52.  21.  65.  52.  25.  45.]]


In [45]:
# All the data in rows, 5,7 and 9.
rows579 = my_data[5:10:2]
print(rows579)

[[ 79.  67.  44. 100.  89.  71.  27.  46.  45.  13.  32.]
 [ 37.  43.  10.  16.  77.  40.  62.   4.  22.  64.  15.]
 [ 80.  93.  76.  46.  46.  35.  57.  70.  93.  36.  86.]]


In [46]:
# All the data in columns 0, 7, 10.
cols = my_data[:,[0,7,10]]
print(cols)

[[ 68.  63.  14.]
 [  5.  77.  33.]
 [  1.   3.  26.]
 [ 83.  32.  96.]
 [ 71.  35.  76.]
 [ 79.  46.  32.]
 [100.  59.   2.]
 [ 37.   4.  15.]
 [ 97.   7.  21.]
 [ 80.  70.  86.]
 [ 25.  65.  45.]]


In [47]:
# The data in columns 1 to 3 (exclusively), from rows 7 to 9 (inclusively).
selected = my_data[7:10, 2]
print(selected)

[10.  8. 76.]


## Exercise 3

In [73]:
from numpy import genfromtxt

with open('SalesData.csv', 'r') as f:
    reader = csv.reader(f, delimiter=',')
    col_headers = next(reader)
    sales_data = np.array(list(reader))

row_headers = sales_data[:,0]
col_headers = np.delete(col_headers, 0)
sales_data = np.delete(sales_data, 0, 1)
sales_data = sales_data.astype('float64') 

print(col_headers)
print(row_headers)
print(sales_data)

['Apr-18' 'May-18' 'Jun-18' 'Jul-18' 'Aug-18' 'Sep-18' 'Oct-18' 'Nov-18'
 'Dec-18' 'Jan-19' 'Feb-19' 'Mar-19']
['L3' 'L1' 'P2' 'N6' 'N4' 'B8']
[[390. 345. 379. 353. 365. 326. 363. 459. 539. 474. 340. 343.]
 [392. 377. 347. 395. 330. 332. 340. 446. 573. 464. 223. 216.]
 [250. 270. 300. 398. 376. 382. 306. 489. 552. 488. 298. 269.]
 [460. 480. 450. 310. 392. 383. 314. 402. 640. 495. 215. 243.]
 [460. 480. 450. 387. 388. 320. 337. 478. 676. 408. 338. 263.]
 [470. 510. 360. 472. 423. 385. 353. 464. 598. 419. 459. 659.]]


In [95]:
# All the sales for the second quarter (Jul-18 to Sep-18 inclusive) calculating the total and the mean for each month.
monthly_sums = np.sum(sales_data, axis=0)
monthly_means = np.mean(sales_data, axis = 0)
second_quarter = monthly_sums[3:6]
print("2nd Quarter Sums:")
for num in monthly_sums[3:6]:
    print(f"{num:.2f}")
print("2nd Quarter Means:")
for num in monthly_means[3:6]:
    print(f"{num:.2f}")

2nd Quarter Sums:
2315.00
2274.00
2128.00
2nd Quarter Means:
385.83
379.00
354.67


In [96]:
# All the sales for stores L3 and L1, 
# for the first and third quarter calculating the total and the mean for each quarter for each store.
